### ISSUE TITLE
Local tests return an error in run_SSN_Utils_Color_SSN test handle

### ISSUE THREAD

**Issue by rbdavid** [EnzymeFunctionInitiative/EFIToolsKBase#57]
The test_run_SSN_Utils_Color_SSN is failing with the below message: 

```
________________ EFIToolsKBaseTest.test_run_SSN_Utils_Color_SSN ________________

self = <EFIToolsKBase_server_test.EFIToolsKBaseTest testMethod=test_run_SSN_Utils_Color_SSN>

    def test_run_SSN_Utils_Color_SSN(self):
>       ret = self.serviceImpl.run_EFI_SSN_Utils_Color_SSN(self.ctx, {
            "ssn_file": "73509/108/3",
            "workspace_name": self.wsName
        })

EFIToolsKBase_server_test.py:161: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../lib/EFIToolsKBase/EFIToolsKBaseImpl.py:232: in run_EFI_SSN_Utils_Color_SSN
    output = cssn.do_analysis(params)
../lib/EFIToolsKBase/ssnutil_wrappers/colorssn.py:44: in do_analysis
    stats = pd.read_csv(os.path.join(self.shared_folder, "stats.txt"), sep="\t", header=None)
/opt/conda3/lib/python3.8/site-packages/pandas/io/parsers.py:688: in read_csv
    return _read(filepath_or_buffer, kwds)
/opt/conda3/lib/python3.8/site-packages/pandas/io/parsers.py:454: in _read
    parser = TextFileReader(fp_or_buf, **kwds)
/opt/conda3/lib/python3.8/site-packages/pandas/io/parsers.py:948: in __init__
    self._make_engine(self.engine)
/opt/conda3/lib/python3.8/site-packages/pandas/io/parsers.py:1180: in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
/opt/conda3/lib/python3.8/site-packages/pandas/io/parsers.py:2010: in __init__
    self._reader = parsers.TextReader(src, **kwds)
pandas/_libs/parsers.pyx:382: in pandas._libs.parsers.TextReader.__cinit__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   FileNotFoundError: [Errno 2] No such file or directory: '/kb/module/work/tmp/stats.txt'

pandas/_libs/parsers.pyx:674: FileNotFoundError
----------------------------- Captured stdout call -----------------------------
N E X T F L O W  ~  version 24.10.3
Launching `/EST/pipelines/colorssn/colorssn.nf` [compassionate_bassi] DSL2 - revision: f9c1c49c85
[ab/3b4d63] Submitted process > color_and_retrieve:get_ssn_id_info
[d4/5766d7] Submitted process > color_and_retrieve:compute_clusters
ERROR ~ Error executing process > 'color_and_retrieve:compute_clusters'

Caused by:
  Process `color_and_retrieve:compute_clusters` terminated with an error exit status (1)


Command executed:

  python /EST/pipelines/colorssn/../shared/python/compute_clusters.py --edgelist edgelist.txt --index-seqid-map index_seqid_map.txt         --clusters cluster_id_map.txt --singletons singletons.txt --cluster-num-map cluster_num_map.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/EST/pipelines/colorssn/../shared/python/compute_clusters.py", line 5, in <module>
      from network import SsnNetworkGraph
    File "/EST/pipelines/shared/python/network.py", line 1, in <module>
      import igraph
  ModuleNotFoundError: No module named 'igraph'

Work dir:
  /kb/module/test/work/d4/5766d7bfc5093814bd398c0d66ffdb

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
/kb/module/work/tmp ['params.yml', 'length.png', 'seqid_source_map.txt', '7b087e25-efeb-4634-bb22-fa2590706ac5', '6abba89b-00e2-4a99-9795-307220fbefa6', '7e71823e-4ef5-43f1-80ee-4b84d0fc841d', 'edge_sm.png', 'all_sequences.fasta', '88c76c5e-ef5b-4efc-b0d2-9a0db5178723', 'e90dccd0-5612-4e05-8ff5-cc38cdbeb4de', 'c09d58a9-134c-40e7-b4fe-70e86c7bd455', 'id_index_map.txt', 'acad751b-383a-4df4-89a3-52f0b517c342', '6fdb6151-ee0a-4bf8-9956-3bf395354268', '98cf6385-7b08-4d4a-bf8c-771dc06e06e2', 'b15c31e7-2d62-4e64-8937-3eda34764429', 'input_sequences.fasta', '1.out.parquet', '1d2c996b-aaa3-478b-b005-bec87574bc0f', 'sunburst_ids.tab', 'ad7de6de-de14-4bab-b65e-b34f8288998b', '0296f17c-7d69-4a53-b9a9-d44568f4f369', '0b351bc0-1216-4b95-bde0-ac617fb826a1', '83b9b1f7-e842-4b6d-9eed-b6cec47a23a3', 'b62426f1-8e84-40ba-bd6d-202a643bd393', '80ecd443-3e32-4fd0-bfda-27c7a41cdb51', 'acc_counts.json', 'pasted_accessions.txt', '57cf9a3b-7427-4698-bedf-abef364c0d67', 'd98aadf2-bc6b-4135-87ae-d8209008c7bb', '76331a77-d2f4-4712-83cc-3057f759fd76', 'aa4d068e-cc9d-4149-a466-f58527bf1e91', 'pident_sm.png', 'b4cc9fc9-65bf-4de7-b963-0d5cf23f0eaa', 'b52b4fbc-6f42-472d-92d3-76ea296a4689', '12bbf63c-7ca4-4b87-98de-7e65a9e9b228', '044d8c26-956a-42bb-99c6-f0ca9b8741db', '1a0dbb0c-dcc0-4069-9fcc-8d85dade15cf', '06755ab3-f37f-497a-b923-771b31c73e6d', '7ebf7929-a24e-4499-96dc-da90e043673d', 'e1415fe1-5297-4d67-9aba-4e0a23d60800', 'sequence_metadata.tab', 'afac1c3b-66f1-4fbb-b4a8-a145390430a4', '64da549a-0a5b-480b-94e8-92baa5e663c6', 'a91c2df3-dff8-4ab0-8dc9-abc7a171d195', '7ca95b1b-5720-4d2c-a72c-120e81c76db9', 'import_stats.json', 'boxplot_stats.parquet', 'query_sequence.fasta', '6d290088-b479-42e4-9da8-20157480e331', 'c2ab75da-e2d8-4650-a5f3-cba92b7c1e9f', 'a71c5f72-521d-408f-8083-0c14e6a3a8e2', '2c697707-e3ec-4946-85e7-5e947bbbcbfd', 'e026089a-b86e-4ff4-aa0f-749a2f553934', 'd94cb1d0-763e-4944-a73c-0d16e52a4d0f', '1f467768-756c-4c18-b057-02520fa254f6', '1dcb5c34-fedb-4849-8688-ab0ce363361f', '63a07899-aa1d-4420-9baf-0884e6ca0ac9', 'b3e9dd9e-af9f-47d7-aaff-1e6a4282b162', '634531df-bc66-44cb-8fac-edd7e7492de7', '720a6e64-0399-4e96-90ae-e7200caa8b30', '5bba42ae-cb6e-47b2-a9d4-5a1e2aa207cc', 'a2bca9f0-e5ba-4167-83c4-543d76bb6f48', 'b37f0ced-6655-49fa-bb99-51b312d4f64a', '525df454-b809-40c3-bfbe-da8b77c4ac06', 'edgelist.txt', '6dafeddb-351e-4717-8690-dcf345215e2d', '394bc38a-2665-4208-ae2d-19789a8a3ec8', '95a6780d-795e-4ef3-b40e-ccc0431bdb1d', 'full_ssn.xgmml', 'edge.png', '99f8ba43-bf57-41c5-ab37-7f06da0ba2ef', 'index_seqid_map.txt', 'length_sm.png', '0726e358-047d-4fbf-bc33-4547912e12f7', '9daf6ffb-695d-44cd-83e9-c5395d44312e', '7d7cf072-ec5b-4ae1-8645-bbe5a04da3d0', 'ae6c5d07-59aa-4fcd-8c98-69a1c384134a', 'seq_mapping.tab', '9fef12a4-5fef-41f4-8822-d3bdcc2852b4', 'fc239ab1-fda1-4db5-b99f-b71ebb21042e', '0c837631-6881-40bd-9166-aa6a1ba471e5', 'evalue.tab', '8ad86c30-093f-447f-9cd9-d1a46bb5ef12', '85b07d3e-d696-44f4-b68a-7ef68900b62d', 'db722f60-49a1-4256-a1d2-7355e2b8b723', '5288fab6-b7fb-477e-b708-e1d87b53b1ca', 'd04bbf67-4c67-4cab-913a-f2367f60e57b', '5d2ff3b9-b019-4780-aefd-dabbbce6bf4f', 'all_files.zip', '2936f1d3-adb1-4118-aa8b-238e7c641c22', 'sequences.fa', '9885c9cb-bdf7-4802-939e-1b075c7656a1', '3507af4e-b453-478f-826a-73395497d19e', 'c4e23c75-5a07-49cb-800f-9bbf7176f789', '95b0b37a-9893-408d-a12a-5688ca0d5fef', '2dfbc6d7-dba4-4487-abc4-01f751f1a209', 'f2fc4ac2-3a26-4435-a3fe-7d434446a42c', '8c7ad6fb-3f47-478a-8756-95169798b196', 'reports', '8653bbb8-2441-4f6d-8e13-9d7cbc84c408', 'dc3f26d3-5063-4061-b1bb-7324d25fb65d', 'pident.png', '61a2e0ec-43bb-4291-8549-a8df5b740227', '3300b1bb-c1fc-4f00-b761-6ec6fb846d81', 'b9172a68-b2e2-4ec3-89d8-1230426577df', 'accession_ids.txt']
--------------------------- Captured stdout teardown ---------------------------
Test workspace was deleted
```

- [ ] As in issue #56, we should reinstate return code catches so that error tracebacks are clear. This is an error happening within the `colorssn.nf` pipeline, specifically in the `compute_clusters()` step. The module `igraph` is imported in the python script that gets run during that nextflow process but that module is never pip installed.

The `igraph` module is listed in the EST `requirements.txt` file but not in the `env.yml` file. The docker image for KBase builds the EST conda environment for nextflow using the EST repo's `env.yml` file. The EFIToolsKBase repo's `requirements.txt` file is then called by a pip install line but this file does not include `igraph`. 

I think the fix for this is to be made on the EST repo side of things, by bringing `env.yml` up to date with the `requirements.txt` file. Will post an issue over there.

**Comment by rbdavid** [comment]
`igraph` is now in the `env.yml` file in the EST repo. Steps to rebuild the KBase docker image:

```bash
docker ps -a # grab the ContainerID for the test/efitoolskbase:latest
docker rm {containerID}
docker images # grab the image ID for test/efitoolskbase:latest
docker rmi {imageID}
docker builder prune # removes all cached data associated with inaccessible docker images/containers
```

**Comment by rbdavid** [comment]
App still failing but no longer due to missing `igraph`.

```
________________ EFIToolsKBaseTest.test_run_SSN_Utils_Color_SSN ________________

self = <EFIToolsKBase_server_test.EFIToolsKBaseTest testMethod=test_run_SSN_Utils_Color_SSN>

    def test_run_SSN_Utils_Color_SSN(self):
>       ret = self.serviceImpl.run_EFI_SSN_Utils_Color_SSN(self.ctx, {
            "ssn_file": "73509/108/3",
            "workspace_name": self.wsName
        })

EFIToolsKBase_server_test.py:161: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../lib/EFIToolsKBase/EFIToolsKBaseImpl.py:232: in run_EFI_SSN_Utils_Color_SSN
    output = cssn.do_analysis(params)
../lib/EFIToolsKBase/ssnutil_wrappers/colorssn.py:55: in do_analysis
    output = self.generate_report({
../lib/EFIToolsKBase/ssnutil_wrappers/colorssn.py:127: in generate_report
    report_info = self.report.create_extended_report(
../lib/installed_clients/KBaseReportClient.py:215: in create_extended_report
    return self._client.run_job('KBaseReport.create_extended_report',
../lib/installed_clients/baseclient.py:253: in run_job
    job_state = self._check_job(mod, job_id)
../lib/installed_clients/baseclient.py:220: in _check_job
    return self._call(self.url, service + '._check_job', [job_id])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <installed_clients.baseclient.BaseClient object at 0x76a1be789520>
url = 'http://172.17.0.2:42089', method = 'KBaseReport._check_job'
params = ['336c3a2c-5921-457e-9d66-b4824ce6fb8e'], context = None

    def _call(self, url, method, params, context=None):
        arg_hash = {'method': method,
                    'params': params,
                    'version': '1.1',
                    'id': str(_random.random())[2:]
                    }
        if context:
            if type(context) is not dict:
                raise ValueError('context is not type dict as required.')
            arg_hash['context'] = context
    
        body = _json.dumps(arg_hash, cls=_JSONObjectEncoder)
        ret = _requests.post(url, data=body, headers=self._headers,
                             timeout=self.timeout,
                             verify=not self.trust_all_ssl_certificates)
        ret.encoding = 'utf-8'
        if ret.status_code == 500:
            if ret.headers.get(_CT) == _AJ:
                err = ret.json()
                if 'error' in err:
>                   raise ServerError(**err['error'])
E                   installed_clients.baseclient.ServerError: Server error: -32000. "KBaseReport parameter validation errors:\n{'file_links': [{0: [{'path': ['does not exist on filesystem']}]}]}\nYour parameters were:\n{ 'direct_html_link_index': 0,\n  'file_links': [ { 'description': 'New SSN file',\n                    'label': 'ssn_out.xgmml',\n                    'name': 'ssn_out.xgmml',\n                    'path': '/kb/module/work/tmp/ssn_out.xgmml'},\n                  { 'description': 'New SSN file',\n                    'label': 'mapping_table.txt',\n                    'name': 'mapping_table.txt',\n                    'path': '/kb/module/work/tmp/mapping_table.txt'}],\n  'html_links': [ { 'description': 'report',\n                    'name': 'index.html',\n                    'path': '/kb/module/work/tmp/reports'}],\n  'message': 'A sample report.',\n  'report_object_name': 'Color_SSN_f23fbabd-39ac-4801-addd-c6f220239322',\n  'workspace_name': 'test_EFIToolsKBase_1734729342822'}"
E                   Traceback (most recent call last):
E                     File "/kb/module/bin/../lib/KBaseReport/KBaseReportServer.py", line 101, in _call_method
E                       result = method(ctx, *params)
E                     File "/kb/module/lib/KBaseReport/KBaseReportImpl.py", line 254, in create_extended_report
E                       params = validate_extended_report_params(params)
E                     File "/kb/module/lib/KBaseReport/utils/validation_utils.py", line 102, in validate_extended_report_params
E                       raise TypeError(_format_errors(validator.errors, params))
E                   TypeError: KBaseReport parameter validation errors:
E                   {'file_links': [{0: [{'path': ['does not exist on filesystem']}]}]}
E                   Your parameters were:
E                   { 'direct_html_link_index': 0,
E                     'file_links': [ { 'description': 'New SSN file',
E                                       'label': 'ssn_out.xgmml',
E                                       'name': 'ssn_out.xgmml',
E                                       'path': '/kb/module/work/tmp/ssn_out.xgmml'},
E                                     { 'description': 'New SSN file',
E                                       'label': 'mapping_table.txt',
E                                       'name': 'mapping_table.txt',
E                                       'path': '/kb/module/work/tmp/mapping_table.txt'}],
E                     'html_links': [ { 'description': 'report',
E                                       'name': 'index.html',
E                                       'path': '/kb/module/work/tmp/reports'}],
E                     'message': 'A sample report.',
E                     'report_object_name': 'Color_SSN_f23fbabd-39ac-4801-addd-c6f220239322',
E                     'workspace_name': 'test_EFIToolsKBase_1734729342822'}

../lib/installed_clients/baseclient.py:187: ServerError
----------------------------- Captured stdout call -----------------------------
N E X T F L O W  ~  version 24.10.3
Launching `/EST/pipelines/colorssn/colorssn.nf` [awesome_albattani] DSL2 - revision: f9c1c49c85
[88/6a72c9] Submitted process > color_and_retrieve:get_ssn_id_info
[8f/f99991] Submitted process > color_and_retrieve:compute_clusters
[ed/ac67cd] Submitted process > color_and_retrieve:get_cluster_stats
[8d/128e85] Submitted process > color_and_retrieve:color_ssn
[7d/f6680f] Submitted process > color_and_retrieve:get_conv_ratio_table
[fd/92d3a6] Submitted process > color_and_retrieve:get_id_list
WARN: Access to undefined parameter `fasta_db` -- Initialise it to a default value eg. `params.fasta_db = some_value`
[3d/8a2a68] Submitted process > color_and_retrieve:get_fasta (5)
[f5/f98e90] Submitted process > color_and_retrieve:get_fasta (2)
[a7/881e64] Submitted process > color_and_retrieve:get_fasta (4)
[0a/b7766a] Submitted process > color_and_retrieve:get_fasta (3)
[8a/2d44a3] Submitted process > color_and_retrieve:get_fasta (9)
[d5/a9e420] Submitted process > color_and_retrieve:get_fasta (7)
[ab/97d0b6] Submitted process > color_and_retrieve:get_fasta (10)
[c3/c16f59] Submitted process > color_and_retrieve:get_fasta (6)
[e1/4bf065] Submitted process > color_and_retrieve:get_fasta (1)
[13/22ee6a] Submitted process > color_and_retrieve:get_fasta (8)
[93/7434c0] Submitted process > color_and_retrieve:get_annotated_mapping_tables
```

This error is happening during the generate_report() method, where the KBaseReport input dict has invalid data. Specifically, the `file_links` input is incorrect, so that narrows debugging to the file path issues.

**Comment by rbdavid** [comment]
Fixed and making a PR.
